### ISSUE TITLE
Don’t refresh conversations when in a message

### ISSUE THREAD

**Issue by elliottetzkorn** [elliottetzkorn/t4t#58]

**Comment by 5five43210** [comment]
don’t get new messages while in convo. t4t @543210_

**Comment by elliottetzkorn** [comment]
> don’t get new messages while in convo. t4t @543210_

Thanks for the message. Are you sure you were not in a network dead zone?

**Comment by 5five43210** [comment]
i don’t think i’m in a network dead zone. i don’t get multiple new messages
while in the conversation, but if i get out the conversation and go back in
i see the new messages

**Comment by elliottetzkorn** [comment]
I see. Which platform are you on, iOS or Android, and are you sure you are on the latest version of the app?

**Comment by 5five43210** [comment]
iOS and i’m on the latest version. might be having issues cause i use a
vpn??

**Comment by elliottetzkorn** [comment]
Interesting, that could be though it would surprise me
