### ISSUE TITLE
Can't update location

### ISSUE THREAD

**Issue by rawpie2** [elliottetzkorn/t4t#77]
Hi, I just got the app and made my profile, I allow precise location but it just says updating... and never gets the location.
I'm using a Pixel 6 pro on Graphene OS, ive allowed the app through everything so its operating as normal.

**Comment by elliottetzkorn** [comment]
Thanks for the heads up, I will look into this!

**Comment by riley-martine** [comment]
Also affected by this, pixel 7 with Graphene OS. Location services are on, wifi/bluetooth scanning enabled, t4t is allowed with precise location while using the app, and other apps are able to access location.

**Comment by elliottetzkorn** [comment]
Thanks for letting me know about this - I will install GrapheneOS on my test device next week and see if I can find out what's going on here. Sorry for the annoyance.

**Comment by rowdyrotifer** [comment]
Also experiencing this on a Pixel 6 with up-to-date GrapheneOS.

It was crashing when using approximate location, and it just hangs forever when using precise location.

**Comment by elliottetzkorn** [comment]
A fix for this is coming soon!

**Comment by elliottetzkorn** [comment]
This should be fixed in the latest version, can anyone confirm?
