### ISSUE TITLE
Android feature request: support multiple notification channels

### ISSUE THREAD

**Issue by riley-martine** [elliottetzkorn/t4t#91]
I would like to disable notifications for post reactions, but not for messages. The way to do this on android is via [notification channels](https://developer.android.com/develop/ui/views/notifications/channels).
Right now when I go to Settings -> Apps -> t4t -> Notifications, there is only a "Miscellaneous" channel. I would like if there was a channel for "post reactions" and one for "messages", so I could control those independently.

**Comment by elliottetzkorn** [comment]
This is actually in the app :). I already anticipated this need! Check out "Notifications" on the profile page!
